### ISSUE TITLE
Add simple Global installation script

### ISSUE THREAD

**Issue by mubaris** [mubaris/Fez#2]
Add a simple script to install the `Fez` globally. Can be shell script.

**Comment by raoasifraza11** [comment]
I found this [tutorial](http://asingh.com.np/blog/fez-installation-and-configuration-guide/) for `fez` installation cloud I write shell script for this? @mubaris

**Comment by mubaris** [comment]
@raoasifraza11 It's not that Fez

**Comment by raoasifraza11** [comment]
Have you any tutorial link I can write in shell/bash.

**Comment by Girbons** [comment]
A `setup.py` should be enough if you want i can submit a PR

**Comment by mubaris** [comment]
@Girbons I think that'll work

**Comment by raajitr** [comment]
is this issue closed?

**Comment by mubaris** [comment]
Sorry, this is closed
